artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Arsalan-Azhar-AI/datasets/raw/refs/heads/main/knowing-person-images-zip.zip
  local_data_file: artifacts/data_ingestion/data.zip
  local_data_file2: celeba-dataset.zip
  unzip_dir: artifacts/data_ingestion
 
data_preprocessing:
  root_dir: artifacts/data_preprocessing
  DATASET: artifacts/data_preprocessing/DATASET
  male_path: artifacts/data_preprocessing/DATASET/male
  female_path: artifacts/data_preprocessing/DATASET/female
  data: artifacts/data_ingestion/list_attr_celeba.csv
  image_folder1: artifacts/data_ingestion/img_align_celeba/img_align_celeba
  folder_name: artifacts/data_ingestion/knowing-person-images

  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  path_of_model: artifacts/training/model.h5
  metric_file_name: metrics.json
